import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "E-commerce API",
      version: "1.0.0",
      description: "E-commerce Backend API Documentation",
    },

    servers: [
      {
        url: "http://localhost:5000/api/v1",
        description: "Development Server",
      },
    ],

    components: {
      parameters: {
        ProductId: {
          in: "path",
          name: "id",
          required: true,
          schema: { type: "string", minLength: 1 },
          description: "Product ID",
        },
        CartItemId: {
          in: "path",
          name: "itemId",
          required: true,
          schema: { type: "string", minLength: 1 },
          description: "Cart item ID owned by the authenticated user",
        },
        WishlistItemId: {
          in: "path",
          name: "itemId",
          required: true,
          schema: { type: "string", minLength: 1 },
          description: "Wishlist item ID owned by the authenticated user",
        },
        PaymentId: { in: "path", name: "paymentId", required: true, schema: { type: "string", minLength: 1 }, description: "Payment ID" },
        OrderId: { in: "path", name: "orderId", required: true, schema: { type: "string", minLength: 1 }, description: "Order ID or order number" },
      },
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      schemas: {
        CheckoutRequest: {
          type: "object",
          additionalProperties: false,
          required: ["customerName", "customerPhone", "address", "deliveryArea", "paymentMethod"],
          properties: {
            customerName: { type: "string", minLength: 2, maxLength: 150 },
            customerPhone: { type: "string", minLength: 7, maxLength: 30 },
            address: { type: "string", minLength: 10, maxLength: 500 },
            deliveryArea: { type: "string", enum: ["INSIDE_DHAKA", "OUTSIDE_DHAKA"] },
            paymentMethod: { type: "string", enum: ["COD", "BKASH", "NAGAD"] },
          },
        },
        CheckoutSummaryItem: {
          type: "object",
          required: ["product", "quantity", "unitPrice", "unitDiscount", "subtotal", "discount", "total"],
          properties: {
            product: { $ref: "#/components/schemas/CommerceProduct" },
            quantity: { type: "integer", minimum: 1 },
            unitPrice: { type: "number" },
            unitDiscount: { type: "number" },
            subtotal: { type: "number" },
            discount: { type: "number" },
            total: { type: "number" },
          },
        },
        CheckoutSummary: {
          type: "object",
          required: ["products", "totalItems", "totalQuantity", "subtotal", "discount", "shippingCharge", "grandTotal"],
          properties: {
            products: { type: "array", items: { $ref: "#/components/schemas/CheckoutSummaryItem" } },
            totalItems: { type: "integer" },
            totalQuantity: { type: "integer" },
            subtotal: { type: "number" },
            discount: { type: "number" },
            shippingCharge: { type: "number" },
            grandTotal: { type: "number" },
          },
        },
        CheckoutSummaryResponse: {
          type: "object",
          required: ["success", "message", "data"],
          properties: {
            success: { type: "boolean", example: true },
            message: { type: "string", example: "Checkout summary retrieved successfully" },
            data: { $ref: "#/components/schemas/CheckoutSummary" },
          },
        },
        CheckoutOrder: {
          allOf: [
            { $ref: "#/components/schemas/CheckoutSummary" },
            { type: "object", required: ["id", "orderNumber", "status", "customerName", "customerEmail", "customerPhone", "address", "deliveryArea", "payment", "createdAt"], properties: {
              id: { type: "string" }, orderNumber: { type: "string" }, status: { type: "string", enum: ["PENDING", "CONFIRMED", "PROCESSING", "PACKED", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"] },
              customerName: { type: "string" }, customerEmail: { type: "string" }, customerPhone: { type: "string" }, address: { type: "string" }, deliveryArea: { type: "string", enum: ["INSIDE_DHAKA", "OUTSIDE_DHAKA"] },
              payment: { type: "object", required: ["id", "method", "status"], properties: { id: { type: "string" }, method: { type: "string", enum: ["COD", "BKASH", "NAGAD"] }, status: { type: "string", enum: ["PENDING", "PAID", "FAILED", "CANCELLED", "REFUNDED"] } } },
              createdAt: { type: "string", format: "date-time" },
            } },
          ],
        },
        CheckoutOrderResponse: {
          type: "object", required: ["success", "message", "data"],
          properties: { success: { type: "boolean", example: true }, message: { type: "string", example: "Checkout completed successfully" }, data: { $ref: "#/components/schemas/CheckoutOrder" } },
        },
        ManualPaymentRequest: {
          type: "object", additionalProperties: false,
          required: ["orderId", "paymentMethod", "senderNumber", "transactionId", "paidAmount"],
          properties: {
            orderId: { type: "string", minLength: 1 }, paymentMethod: { type: "string", enum: ["BKASH", "NAGAD"] }, senderNumber: { type: "string", minLength: 7, maxLength: 30 }, transactionId: { type: "string", minLength: 5, maxLength: 100 }, paidAmount: { type: "number", exclusiveMinimum: 0 }, paymentScreenshot: { type: "string", nullable: true, maxLength: 2048 },
          },
        },
        RejectPaymentRequest: { type: "object", additionalProperties: false, required: ["reason"], properties: { reason: { type: "string", minLength: 3, maxLength: 500 } } },
        RefundPaymentRequest: { type: "object", additionalProperties: false, required: ["reason"], properties: { reason: { type: "string", minLength: 3, maxLength: 500 } } },
        Payment: {
          type: "object", required: ["id", "orderId", "orderNumber", "method", "status", "senderNumber", "transactionId", "paidAmount", "paymentScreenshot", "rejectionReason", "refundReason", "totalAmount", "verifiedAt", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" }, orderId: { type: "string" }, orderNumber: { type: "string" }, method: { type: "string", enum: ["COD", "BKASH", "NAGAD"] }, status: { type: "string", enum: ["PENDING", "PAID", "FAILED", "CANCELLED", "REFUNDED"] }, senderNumber: { type: "string", nullable: true }, transactionId: { type: "string", nullable: true }, paidAmount: { type: "number", nullable: true }, paymentScreenshot: { type: "string", nullable: true }, rejectionReason: { type: "string", nullable: true }, refundReason: { type: "string", nullable: true }, totalAmount: { type: "number" }, verifiedAt: { type: "string", format: "date-time", nullable: true }, createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" },
          },
        },
        PaymentSuccessResponse: { type: "object", required: ["success", "message", "data"], properties: { success: { type: "boolean", example: true }, message: { type: "string", example: "Payment retrieved successfully" }, data: { $ref: "#/components/schemas/Payment" } } },
        PaymentListResponse: { type: "object", required: ["success", "message", "data"], properties: { success: { type: "boolean", example: true }, message: { type: "string", example: "Payments retrieved successfully" }, data: { type: "object", required: ["items", "meta"], properties: { items: { type: "array", items: { $ref: "#/components/schemas/Payment" } }, meta: { type: "object", required: ["page", "limit", "total", "totalPages"], properties: { page: { type: "integer" }, limit: { type: "integer" }, total: { type: "integer" }, totalPages: { type: "integer" } } } } } } },
        OrderStatusRequest: {
          type: "object", additionalProperties: false, required: ["status"],
          properties: { status: { type: "string", enum: ["CONFIRMED", "PROCESSING", "PACKED", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"] }, adminNote: { type: "string", nullable: true } },
        },
        AddCartItemRequest: {
          type: "object",
          additionalProperties: false,
          required: ["productId", "quantity"],
          properties: {
            productId: { type: "string", minLength: 1 },
            quantity: { type: "integer", minimum: 1 },
          },
          example: { productId: "cmproduct123", quantity: 2 },
        },
        UpdateCartItemRequest: {
          type: "object",
          additionalProperties: false,
          required: ["quantity"],
          properties: { quantity: { type: "integer", minimum: 1 } },
          example: { quantity: 5 },
        },
        AddWishlistItemRequest: {
          type: "object",
          additionalProperties: false,
          required: ["productId"],
          properties: { productId: { type: "string", minLength: 1 } },
          example: { productId: "cmproduct123" },
        },
        CommerceProduct: {
          type: "object",
          required: ["id", "title", "slug", "thumbnailImage", "productCode", "shortDescription", "customerSellPrice", "salePrice", "status"],
          properties: {
            id: { type: "string" },
            title: { type: "string" },
            slug: { type: "string" },
            thumbnailImage: { type: "string" },
            productCode: { type: "string" },
            shortDescription: { type: "string" },
            customerSellPrice: { type: "number" },
            salePrice: { type: "number", nullable: true },
            resellerPrice: { type: "number", description: "Only included for reseller/admin roles" },
            status: { type: "string", enum: ["DRAFT", "ACTIVE", "INACTIVE", "ARCHIVED"] },
          },
          example: { id: "cmproduct123", title: "Wireless Mouse", slug: "wireless-mouse", thumbnailImage: "/uploads/products/thumbnails/mouse.webp", productCode: "MOUSE-001", shortDescription: "Ergonomic wireless mouse for daily use.", customerSellPrice: 1500, salePrice: 1350, resellerPrice: 1200, status: "ACTIVE" },
        },
        CartItem: {
          type: "object",
          required: ["id", "quantity", "unitPrice", "unitDiscount", "lineSubtotal", "lineDiscount", "lineTotal", "product", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            quantity: { type: "integer" },
            unitPrice: { type: "number" },
            unitDiscount: { type: "number" },
            lineSubtotal: { type: "number" },
            lineDiscount: { type: "number" },
            lineTotal: { type: "number" },
            product: { $ref: "#/components/schemas/CommerceProduct" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Cart: {
          type: "object",
          required: ["id", "items", "summary", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            items: { type: "array", items: { $ref: "#/components/schemas/CartItem" } },
            summary: {
              type: "object",
              required: ["totalItems", "totalQuantity", "subtotal", "discount", "grandTotal"],
              properties: {
                totalItems: { type: "integer" },
                totalQuantity: { type: "integer" },
                subtotal: { type: "number" },
                discount: { type: "number" },
                grandTotal: { type: "number" },
              },
            },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        CartSuccessResponse: {
          type: "object",
          required: ["success", "message", "data"],
          properties: {
            success: { type: "boolean", example: true },
            message: { type: "string", example: "Cart retrieved successfully" },
            data: { $ref: "#/components/schemas/Cart" },
          },
        },
        WishlistItem: {
          type: "object",
          required: ["id", "product", "createdAt"],
          properties: {
            id: { type: "string" },
            product: { $ref: "#/components/schemas/CommerceProduct" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Wishlist: {
          type: "object",
          required: ["id", "items", "totalItems", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            items: { type: "array", items: { $ref: "#/components/schemas/WishlistItem" } },
            totalItems: { type: "integer" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        WishlistSuccessResponse: {
          type: "object",
          required: ["success", "message", "data"],
          properties: {
            success: { type: "boolean", example: true },
            message: { type: "string", example: "Wishlist retrieved successfully" },
            data: { $ref: "#/components/schemas/Wishlist" },
          },
        },
        ProductAttribute: {
          type: "object",
          additionalProperties: false,
          required: ["name", "values"],
          properties: {
            name: { type: "string", minLength: 1, maxLength: 50 },
            values: { type: "array", minItems: 1, maxItems: 100, items: { type: "string", minLength: 1, maxLength: 100 } },
          },
        },
        ProductFields: {
          type: "object",
          additionalProperties: false,
          properties: {
            title: { type: "string", minLength: 2, maxLength: 200 },
            shortDescription: { type: "string", minLength: 10, maxLength: 500 },
            description: { type: "string", minLength: 10, maxLength: 20000 },
            category: { type: "string", minLength: 1, maxLength: 100 },
            costPrice: { type: "number", exclusiveMinimum: 0 },
            customerSellPrice: { type: "number", exclusiveMinimum: 0 },
            resellerPrice: { type: "number", exclusiveMinimum: 0 },
            salePrice: { type: "number", exclusiveMinimum: 0, nullable: true },
            discountType: { type: "string", enum: ["PERCENTAGE", "FIXED"], nullable: true },
            discountValue: { type: "number", minimum: 0, nullable: true },
            taxRate: { type: "number", minimum: 0, maximum: 100, nullable: true },
            couponCode: { type: "string", minLength: 1, maxLength: 100, nullable: true },
            productCode: { type: "string", minLength: 1, maxLength: 100, pattern: "^[A-Za-z0-9._-]+$" },
            barcode: { type: "string", minLength: 1, maxLength: 100, nullable: true },
            attributes: { type: "array", maxItems: 30, items: { $ref: "#/components/schemas/ProductAttribute" } },
            enableSize: { type: "boolean", description: "Show and apply the Size selector for this product" },
            availableSizes: { type: "array", maxItems: 7, uniqueItems: true, items: { type: "string", enum: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"] }, description: "Required when enableSize is true; ignored when false" },
            status: { type: "string", enum: ["DRAFT", "ACTIVE", "INACTIVE", "ARCHIVED"] },
            thumbnailImage: { type: "string", minLength: 1, maxLength: 2048, description: "jpg, jpeg, png, or webp path/URL" },
            productImages: { type: "array", maxItems: 10, items: { type: "string", minLength: 1, maxLength: 2048 } },
            productVideos: { type: "array", maxItems: 5, items: { type: "string", minLength: 1, maxLength: 2048 } },
            isFeatured: { type: "boolean" },
          },
        },
        ProductWriteRequest: {
          allOf: [{ $ref: "#/components/schemas/ProductFields" }],
          required: ["title", "shortDescription", "description", "category", "costPrice", "customerSellPrice", "resellerPrice", "productCode", "thumbnailImage"],
        },
        ProductPatchRequest: {
          allOf: [{ $ref: "#/components/schemas/ProductFields" }],
          minProperties: 1,
        },
        RatingBreakdown: {
          type: "object",
          required: ["1", "2", "3", "4", "5"],
          properties: {
            "1": { type: "integer", minimum: 0 },
            "2": { type: "integer", minimum: 0 },
            "3": { type: "integer", minimum: 0 },
            "4": { type: "integer", minimum: 0 },
            "5": { type: "integer", minimum: 0 },
          },
        },
        ProductLatestReview: {
          type: "object",
          required: ["id", "reviewerName", "rating", "comment", "images", "createdAt"],
          properties: {
            id: { type: "string" },
            reviewerName: { type: "string", nullable: true },
            rating: { type: "integer", minimum: 1, maximum: 5 },
            comment: { type: "string", nullable: true },
            images: { type: "array", items: { type: "string" } },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        ProductResponse: {
          type: "object",
          required: ["id", "title", "shortDescription", "description", "slug", "productCode", "barcode", "category", "customerSellPrice", "salePrice", "discountType", "discountValue", "taxRate", "couponCode", "attributes", "enableSize", "availableSizes", "thumbnailImage", "productImages", "productVideos", "status", "isFeatured", "averageRating", "reviewCount", "ratingBreakdown", "latestReviews", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            title: { type: "string" },
            shortDescription: { type: "string" },
            description: { type: "string" },
            slug: { type: "string" },
            productCode: { type: "string" },
            barcode: { type: "string", nullable: true },
            category: { type: "string" },
            costPrice: { type: "number", description: "Admin-only internal field" },
            customerSellPrice: { type: "number" },
            resellerPrice: { type: "number", description: "Returned only to reseller/admin users" },
            salePrice: { type: "number", nullable: true },
            discountType: { type: "string", enum: ["PERCENTAGE", "FIXED"], nullable: true },
            discountValue: { type: "number", nullable: true },
            taxRate: { type: "number", nullable: true },
            couponCode: { type: "string", nullable: true },
            attributes: { type: "array", items: { $ref: "#/components/schemas/ProductAttribute" } },
            enableSize: { type: "boolean" },
            availableSizes: { type: "array", items: { type: "string" } },
            thumbnailImage: { type: "string" },
            productImages: { type: "array", items: { type: "string" } },
            productVideos: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["DRAFT", "ACTIVE", "INACTIVE", "ARCHIVED"] },
            isFeatured: { type: "boolean" },
            averageRating: { type: "number", minimum: 0, maximum: 5 },
            reviewCount: { type: "integer", minimum: 0 },
            ratingBreakdown: { $ref: "#/components/schemas/RatingBreakdown" },
            latestReviews: { type: "array", items: { $ref: "#/components/schemas/ProductLatestReview" } },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
          example: {
            id: "cmproduct123",
            title: "Wireless Gaming Mouse",
            shortDescription: "Ergonomic wireless mouse for work and gaming.",
            description: "High precision wireless gaming mouse with a rechargeable battery and programmable controls.",
            slug: "wireless-gaming-mouse",
            productCode: "MOUSE-001",
            barcode: "8901234567890",
            category: "Electronics",
            costPrice: 800,
            customerSellPrice: 1500,
            resellerPrice: 1200,
            salePrice: 1350,
            discountType: "PERCENTAGE",
            discountValue: 10,
            taxRate: 5,
            couponCode: "SUMMER10",
            attributes: [{ name: "Colour", values: ["Black", "White"] }],
            enableSize: true,
            availableSizes: ["S", "M", "L", "XL"],
            thumbnailImage: "/uploads/products/thumbnails/mouse.webp",
            productImages: ["/uploads/products/images/mouse-front.webp"],
            productVideos: ["/uploads/products/videos/mouse-demo.mp4"],
            status: "ACTIVE",
            isFeatured: true,
            averageRating: 4.5,
            reviewCount: 2,
            ratingBreakdown: { "1": 0, "2": 0, "3": 0, "4": 1, "5": 1 },
            latestReviews: [{ id: "cmreview123", reviewerName: "Customer", rating: 5, comment: "Excellent product", images: [], createdAt: "2026-07-28T00:00:00.000Z" }],
            createdAt: "2026-07-28T00:00:00.000Z",
            updatedAt: "2026-07-28T00:00:00.000Z",
          },
        },
        Review: {
          type: "object",
          properties: {
            id: { type: "string" },
            productId: { type: "string" },
            orderId: { type: "string" },
            orderItemId: { type: "string" },
            userId: { type: "string" },
            rating: { type: "integer", minimum: 1, maximum: 5 },
            comment: { type: "string", nullable: true },
            images: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["APPROVED", "HIDDEN"] },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        PublicReview: {
          type: "object",
          properties: {
            id: { type: "string" },
            reviewerName: { type: "string", nullable: true },
            reviewerProfileImage: { type: "string", nullable: true },
            rating: { type: "integer" },
            comment: { type: "string", nullable: true },
            images: { type: "array", items: { type: "string" } },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        AdminReviewView: {
          type: "object",
          properties: {
            id: { type: "string" },
            productId: { type: "string" },
            productCode: { type: "string", nullable: true },
            productName: { type: "string", nullable: true },
            orderCode: { type: "string", nullable: true },
            orderId: { type: "string" },
            customerName: { type: "string", nullable: true },
            customerEmail: { type: "string", nullable: true },
            customerPhone: { type: "string", nullable: true },
            rating: { type: "integer" },
            comment: { type: "string", nullable: true },
            images: { type: "array", items: { type: "string" } },
            status: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
      },
    },

    security: [
      {
        bearerAuth: [],
      },
    ],
  },

  apis: ["./src/modules/**/*.route.ts"],
};

export const swaggerSpec = swaggerJsdoc(options);
